### ISSUE TITLE
Please add function: int scoreFor(Category cat, int[] dice)

### ISSUE THREAD

**Issue by ckoppelman** [Mego/Yahtzee#1]
This will help everyone from having to rewrite the same code to prioritize points.

**Comment by ckoppelman** [comment]
Or perhaps better, Map<Category, Function<int[], Integer>>

**Comment by Mego** [comment]
This already exists as [`Category.getScore(int[] dice)`](https://github.com/Mego/Yahtzee/blob/master/src/mego/yahtzee/Category.java#L64).
